### ISSUE TITLE
FE: CSS 관리 방식 (CSSinJS | CSSinCSS | CSSModule)

### ISSUE THREAD

**Issue by RandomlyChristen** [softeerbootcamp/Team4-AutoBid#40]
# 제목

# 세부 구현 내용

# 예상되는 주의사항

**Comment by hyunrice98** [comment]
css conflict와 관련해서 조사를 좀 해봤습니다.

- css module은 react module과 함께 쓰기 위함이며, html 깡으로 된거와 사용하기 위해선 과정이 꽤 복잡하다. [관련 SO 질문](https://stackoverflow.com/questions/55058937/using-css-loader-without-react)

- CSS-in-JS와 같은 경우, JS 내부가 길어지고 불분명해지는 경우가 다수 있어, 정말 잘 관리된 페이지 및 큰 페이지가 아니라면 cost-effective하지 않다. (styled-component 의 경우)

- 이대로 진행하게 된다면 머지 컨플릭트를 유발할 수는 있으나, BEM 네이밍 컨벤션이 철저히 지켜진다면 (컴포넌트간의 간섭을 최대로 줄이는것 전제), 최소한의 컨플릭트로 개발을 진행 할 수 있을 것이라 기대됨.

한줄요약: BEM은 위대하다
